# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ashley Connor's Blog
email: me@ashleyconnor.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The idle thoughts of a rambling developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://ashleyconnor.co.uk # the base hostname & protocol for your site
locale: en
# theme options
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      show_date: true
words_per_minute: 200
paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name: Ashley Connor
  avatar: /assets/images/avatar.jpg
  email: me@ashleyconnor.co.uk
  twitter: ashconnor
  github: ashleyconnor
  linkedin: ashleyconnor
  location: Toronto, Canada
  stackoverflow: 196834/ash

# Social Sharing
twitter:
  username: &twitter ashconnor
# facebook:
#   username               : &facebook "ashleyconnor"
#   app_id                 :
#   publisher              :
og_image: /assets/images/avatar.jpg

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-twitter-plugin
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - _pages
  - plugins
  - vendor
