# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ashley Connor
email: ashconnor@me.com
description: > # this means to ignore newlines until "baseurl:"
  The idle thoughts of a rambling developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashleyconnor.co.uk" # the base hostname & protocol for your site

# theme options
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name   : "Ashley Connor"
  avatar : "/assets/images/avatar.jpg"
  email  : # optional
  uri    : http://ashleyconnor.co.uk
  twitter: ashconnor
  reddit : ashconnor
  github : ashleyconnor
  keybase: ashconnor
  location: Toronto, Canada
  stackoverflow: 196834/ash
  linkedin: ashleyconnor

# Social Sharing
twitter:
  username               : &twitter "ashconnor"
# facebook:
#   username               : &facebook "ashleyconnor"
#   app_id                 :
#   publisher              :
og_image                 : "/assets/images/site-logo.png"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
