# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Jekyll AWS Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_to_aws:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Build blog
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build -d public/
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1
    - name: Deploy to S3
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:  |
        echo "Copying files to server..."
        aws s3 sync public/ "s3://ashleyconnor.co.uk" --size-only --exclude "*" --include "*.*" --delete
    - name: Clear CloudFront cache
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws cloudfront create-invalidation --distribution-id "ELC75LY8LAL5J" --paths '/*'
        aws cloudfront create-invalidation --distribution-id "E3BX794VKKZWKT" --paths '/*'
